version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped