[phases.setup]
nixPkgs = ['nodejs-22.13.0', 'nodePackages.npm']

[phases.install]
cmds = ['npm install', 'cd new-nextjs-app && npm install']

[phases.build]
cmds = ['cd new-nextjs-app && npm run build']

[start]
cmd = 'node server.js'