[build]
builder = "nixpacks"
provider = "railwayapp/nixpacks:edge"  # Use the latest version
buildCommand = "npm run install-all && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[environments]
NODE_ENV = "production"