[build]
builder = "docker"

[deploy]
startCommand = "pm2-runtime start ecosystem.config.js --env production"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300

[environments]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
NEXT_TELEMETRY_DISABLED = "1"
DISABLE_ESLINT_PLUGIN = "true"
SKIP_ENV_VALIDATION = "true"