[build]
builder = "nixpacks"
buildCommand = "npm run install-all && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[environments]
NODE_ENV = "production"