[build]
builder = "docker"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100

[environments]
NODE_ENV = "production"
CLIENT_DIST_DIR = "/app/client/dist"